/* inc/config_osi2.h.  Generated by configure.  */
/* inc/config_osi2.h.in.  Generated from configure.ac by autoheader.  */

/* If defined, the Ampl Solver Library is available. */
/* #undef COIN_HAS_ASL */

/* Define to 1 if the Cbc package is used */
#define COIN_HAS_CBC 1

/* Define to 1 if the Cgl package is used */
#define COIN_HAS_CGL 1

/* Define to 1 if the Clp package is used */
#define COIN_HAS_CLP 1

/* Define to 1 if the CoinUtils package is used */
#define COIN_HAS_COINUTILS 1

/* Define to 1 if the Cplex package is used */
/* #undef COIN_HAS_CPX */

/* Define to 1 if the Glpk package is used */
/* #undef COIN_HAS_GLPK */

/* Define to 1 if the Lindo package is used */
/* #undef COIN_HAS_LINDO */

/* Define to 1 if the OS package is used */
#define COIN_HAS_OS 1

/* Define to 1 if the Osi package is used */
#define COIN_HAS_OSI 1

/* Define to 1 if the Osi2 package is used */
#define COIN_HAS_OSI2 1

/* Define to 1 if readline is available */
/* #undef COIN_HAS_READLINE */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <readline/readline.h> header file. */
/* #undef HAVE_READLINE_READLINE_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "osi2"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "coin-osi2@list.coin-or.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Osi2"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Osi2 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "osi2"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.1"
